---
# QEMU Guest Agent
- name: Install Guest Agent
  apt:
    name:
      - qemu-guest-agent
    update_cache: true
    state: present

- include_tasks: docker.yml
  when: "'docker_servers' in group_names"
