version: '3'
services:
  recipes_db:
    container_name: recipes_db
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./tandoor.env

  recipes_web:
    container_name: recipes_web
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./tandoor.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - recipes_db

  recipes_nginx:
    container_name: recipes_nginx
    image: nginx:mainline-alpine
    restart: always
    env_file:
      - ./tandoor.env
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro
    ports:
      - 1080:80
    depends_on:
      - web_recipes

volumes:
  nginx_config:
  staticfiles:
